imageTag: pythia_4_7 # change this to the docker image tag you want

chain:
  chain_id: TESTING
  chain_name: aptos-multi-region-bench
  era: 7 # bump this to wipe the chain

# haproxy disabled, and hit the validators and VFN LBs directly
# If you want to enable haproxy, you may want to change the validator and fullnode
# service types to ClusterIP to save on costs and redundant infra.
haproxy:
  enabled: false

# to run experiments as root
podSecurityPolicy: false
enablePrivilegedMode: true

# haproxy disabled, so validator and VFN get their own LoadBalancer directly
service:
  validator:
    internal:
      type: LoadBalancer
  fullnode:
    internal:
      type: LoadBalancer

# the validator configuration
validator:
  enableNetworkPolicy: false # haproxy disabled, we need to disable the default NetworkPolicy to enable validator discovery
    # affinity:
    #podAntiAffinity:
    #  requiredDuringSchedulingIgnoredDuringExecution:
    #    - labelSelector:
    #        matchExpressions:
    #          - key: app.kubernetes.io/name
    #            operator: In
    #            values:
    #              - validator
    #      topologyKey: kubernetes.io/hostname
  image:
    repo: galexo/validator
  resources:
    limits:
      cpu: "10"
      memory: 10Gi
    requests:
      cpu: "10"
      memory: 10Gi
  storage:
    class: gp3
    size: 100Gi
  config:
    consensus:
      max_sending_block_txns: 10000
      max_receiving_block_txns: 16000
      max_sending_block_bytes: 10000000
      max_receiving_block_bytes: 15000000
        # quorum_store_configs:
        # max_batch_counts: 300
        # mempool_txn_pull_max_count: 300
        # mempool_txn_pull_max_bytes: 1000000
        # back_pressure_local_batch_num: 10
    execution:
      processed_transactions_detailed_counters: true
      concurrency_level: 5
    state_sync:
      state_sync_driver:
        bootstrapping_mode: ApplyTransactionOutputsFromGenesis
        continuous_syncing_mode: ApplyTransactionOutputs
      storage_service:
        max_network_chunk_bytes: 20971520
        max_transaction_output_chunk_size: 5000
      data_streaming_service:
        max_concurrent_requests: 20
    storage:
      rocksdb_configs:
        use_state_kv_db: true
    validator_network:
      max_frame_size: 20971520


# the VFN configuration
fullnode:
  #  affinity:
  #  podAntiAffinity:
  #    requiredDuringSchedulingIgnoredDuringExecution:
  #      - labelSelector:
  #          matchExpressions:
  #            - key: app.kubernetes.io/name
  #              operator: In
  #              values:
  #                - fullnode
  #        topologyKey: kubernetes.io/hostname
  image:
    repo: galexo/validator
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "2"
      memory: 4Gi
  storage:
    class: gp3
    size: 100Gi
  config:
    api:
      max_submit_transaction_batch_size: 100
    execution:
      processed_transactions_detailed_counters: true
    storage:
      rocksdb_configs:
        use_state_kv_db: true
