imageTag: performance_0704776e507d62c9704829e150b912d94b318d4f # change this to the docker image tag you want

chain:
  chain_id: TESTING
  chain_name: aptos-multi-region-bench
  era: 80 # bump this to wipe the chain

# haproxy disabled, and hit the validators and VFN LBs directly
# If you want to enable haproxy, you may want to change the validator and fullnode
# service types to ClusterIP to save on costs and redundant infra.
haproxy:
  enabled: false

# to run experiments as root
podSecurityPolicy: false
enablePrivilegedMode: true

# haproxy disabled, so validator and VFN get their own LoadBalancer directly
service:
  validator:
    internal:
      type: LoadBalancer
  fullnode:
    internal:
      type: LoadBalancer

# the validator configuration
validator:
  enableNetworkPolicy: false # haproxy disabled, we need to disable the default NetworkPolicy to enable validator discovery
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: cloud.google.com/machine-family
                operator: In
                values:
                  - t2d
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/part-of
                operator: In
                values:
                  - aptos-node
          topologyKey: kubernetes.io/hostname
  image:
    repo: us-west1-docker.pkg.dev/aptos-global/aptos-internal/validator
  resources:
    limits:
      cpu: "42"
      memory: 64Gi
    requests:
      cpu: "42"
      memory: 64Gi
  storage:
    class: ssd
    size: 1000Gi
  config:
    execution:
      processed_transactions_detailed_counters: true
      concurrency_level: 24

# the VFN configuration
fullnode:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: cloud.google.com/machine-family
                operator: In
                values:
                  - t2d
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/part-of
                operator: In
                values:
                  - aptos-node
          topologyKey: kubernetes.io/hostname
  image:
    repo: us-west1-docker.pkg.dev/aptos-global/aptos-internal/validator
  resources:
    limits:
      cpu: "13"
      memory: 32Gi
    requests:
      cpu: "13"
      memory: 32Gi
  storage:
    class: ssd
    size: 1000Gi
  config:
    api:
      max_submit_transaction_batch_size: 100
    execution:
      processed_transactions_detailed_counters: true
