apiVersion: v1
kind: Pod
metadata:
  name: loadtest
spec:
  containers:
  - command:
    - aptos-transaction-emitter
    - emit-tx
    - --mint-key=0xE25708D90C72A53B400B27FC7602C4D546C7B7469FA6E12544F0EBFB2F16AE19
    - --chain-id=7
    - --targets=http://adbd6be7a28554ecfa54325aca7a45ea-1935913171.us-east-1.elb.amazonaws.com:8080
    - --targets=http://ada038b55773645a1ac629fb9379ae2b-424819234.us-east-1.elb.amazonaws.com:8080
    - --targets=http://a1b70dbc832cf41feb1ea78a5f8981b1-1732401864.us-east-1.elb.amazonaws.com:8080
    - --targets=http://a1fcc5c0e35fc44dbbe918249d33c221-82111845.us-east-1.elb.amazonaws.com:8080
    - --mempool-backlog=5000
    - --duration=300
    - --expected-max-txns=6000000
    - --txn-expiration-time-secs=90
    - --max-transactions-per-account=1
    - --workers-per-endpoint=90
    - --accounts-per-worker=300
    - --transaction-type
    - solana
    env:
    - name: RUST_BACKTRACE
      value: '1'
    - name: REUSE_ACC
      value: '1'
    image: raycoms/tools:py_13_09
    name: loadtest
    resources:
      limits:
        cpu: '8'
        memory: 10Gi
      requests:
        cpu: '8'
        memory: 10Gi
  restartPolicy: Never
