apiVersion: v1
kind: Pod
metadata:
  name: loadtest
spec:
  containers:
  - command:
    - aptos-transaction-emitter
    - emit-tx
    - --mint-key=0xE25708D90C72A53B400B27FC7602C4D546C7B7469FA6E12544F0EBFB2F16AE19
    - --chain-id=7
    - --targets=http://ac7e8ee14b4c7481299e3c432d9dfbee-1967138314.us-east-1.elb.amazonaws.com:8080
    - --targets=http://a001a547556174269b3a4086a4666c82-1398467085.us-east-1.elb.amazonaws.com:8080
    - --targets=http://a992757d30b944545bf71d523c7ddd84-488198590.us-east-1.elb.amazonaws.com:8080
    - --targets=http://afb4aff353fad4851869caee00398ff2-873121079.us-east-1.elb.amazonaws.com:8080
    - --mempool-backlog=500000
    - --duration=300
    - --expected-max-txns=6000000
    - --txn-expiration-time-secs=160
    - --max-transactions-per-account=1
    - --workers-per-endpoint=6000
    - --accounts-per-worker=4
    - --transaction-type
    - solana
    env:
    - name: RUST_BACKTRACE
      value: '1'
    - name: REUSE_ACC
      value: '1'
    image: raycoms/tools:newpy_12_10
    name: loadtest
    resources:
      limits:
        cpu: '20'
        memory: 64Gi
      requests:
        cpu: '20'
        memory: 64Gi
  restartPolicy: Never
