apiVersion: v1
kind: Pod
metadata:
  name: loadtest
spec:
  containers:
  - command:
    - aptos-transaction-emitter
    - emit-tx
    - --mint-key=0xE25708D90C72A53B400B27FC7602C4D546C7B7469FA6E12544F0EBFB2F16AE19
    - --chain-id=7
    - --targets=http://aafd55a4adb6c46ceaeeab0e16dfa3aa-866884286.us-west-1.elb.amazonaws.com:8080
    - --targets=http://a8a6b15c2cb0a4944be59cc510a7aa45-1356628656.us-west-1.elb.amazonaws.com:8080
    - --targets=http://a7eb01f4997fc4182a823a81eff39282-1321830241.us-west-1.elb.amazonaws.com:8080
    - --targets=http://aa3bfaddf60954faeb770c479703a620-589907351.us-west-1.elb.amazonaws.com:8080
    - --mempool-backlog=25000
    - --duration=300
    - --expected-max-txns=6000000
    - --txn-expiration-time-secs=300
    - --max-transactions-per-account=1
    - --transaction-type
    - dexbursty
    env:
    - name: RUST_BACKTRACE
      value: '1'
    - name: REUSE_ACC
      value: '1'
    image: galexo/tools:17_5_1400
    name: loadtest
    resources:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: '2'
        memory: 4Gi
  restartPolicy: Never
