apiVersion: v1
kind: Pod
metadata:
  name: loadtest
spec:
  containers:
  - command:
    - aptos-transaction-emitter
    - emit-tx
    - --mint-key=0xE25708D90C72A53B400B27FC7602C4D546C7B7469FA6E12544F0EBFB2F16AE19
    - --chain-id=7
    - --targets=http://ac3c285d8e286484fb9c097fcd1704c6-1340184815.us-west-1.elb.amazonaws.com:8080
    - --targets=http://a5dc0dd3bcf7444abaa60bb1841923d3-454246155.us-west-1.elb.amazonaws.com:8080
    - --targets=http://aa8d9610fd72a49e0b220203792a2f57-1291702521.us-west-1.elb.amazonaws.com:8080
    - --targets=http://ac74ef2c52361473fa96e17444894379-1817880849.us-west-1.elb.amazonaws.com:8080
    - --mempool-backlog=1000
    - --duration=120
    - --expected-max-txns=2400000
    - --txn-expiration-time-secs=60
    - --max-transactions-per-account=1
    - --transaction-type
    - dexbursty
    env:
    - name: RUST_BACKTRACE
      value: '1'
    - name: REUSE_ACC
      value: '1'
    image: galexo/tools:17_5_1400
    name: loadtest
    resources:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: '2'
        memory: 4Gi
  restartPolicy: Never
