apiVersion: v1
kind: Pod
metadata:
  name: loadtest
spec:
  containers:
  - command:
    - aptos-transaction-emitter
    - emit-tx
    - --mint-key=0xE25708D90C72A53B400B27FC7602C4D546C7B7469FA6E12544F0EBFB2F16AE19
    - --chain-id=7
    - --targets=http://a3224237b72fe4710a136bfa69c1b3fd-703429561.us-west-1.elb.amazonaws.com:8080
    - --targets=http://a2fe5e5b9cd4349cb853c14595c92e1e-1661966379.us-west-1.elb.amazonaws.com:8080
    - --targets=http://a17d5cb44f26f497abcbf860ec2e933b-2060101718.us-west-1.elb.amazonaws.com:8080
    - --targets=http://a0bc0ed60e3304cb0a79e53e69a5ef0b-724812733.us-west-1.elb.amazonaws.com:8080
    - --mempool-backlog=25000
    - --duration=300
    - --expected-max-txns=6000000
    - --txn-expiration-time-secs=300
    - --max-transactions-per-account=1
    - --transaction-type
    - dexbursty
    env:
    - name: RUST_BACKTRACE
      value: '1'
    - name: REUSE_ACC
      value: '1'
    image: galexo/tools:17_5_1400
    name: loadtest
    resources:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: '2'
        memory: 4Gi
  restartPolicy: Never
