apiVersion: v1
kind: Pod
metadata:
  name: loadtest
spec:
  containers:
  - command:
    - aptos-transaction-emitter
    - emit-tx
    - --mint-key=0xE25708D90C72A53B400B27FC7602C4D546C7B7469FA6E12544F0EBFB2F16AE19
    - --chain-id=7
    - --targets=http://a434c95c5058643588fbd706c9948271-1468350746.us-east-1.elb.amazonaws.com:8080
    - --targets=http://a9177b1a88169444880c2b494f5fbd07-452971272.us-east-1.elb.amazonaws.com:8080
    - --targets=http://a49eb409552a84c788262f6d2a6182d9-2055469196.us-east-1.elb.amazonaws.com:8080
    - --targets=http://aaf43527c2ebb4738ba06dc743d40593-712039011.us-east-1.elb.amazonaws.com:8080
    - --mempool-backlog=25000
    - --duration=300
    - --expected-max-txns=6000000
    - --txn-expiration-time-secs=60
    - --max-transactions-per-account=1
    - --workers-per-endpoint=50
    - --accounts-per-worker=400
    - --transaction-type
    - solana
    env:
    - name: RUST_BACKTRACE
      value: '1'
    - name: REUSE_ACC
      value: '1'
    image: galexo/tools:05_09
    name: loadtest
    resources:
      limits:
        cpu: '8'
        memory: 10Gi
      requests:
        cpu: '8'
        memory: 10Gi
  restartPolicy: Never
